FROM golang:1.25-alpine
RUN apk add --no-cache git curl
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV PORT=8080
EXPOSE 8080
CMD ["air", "-c", ".air.server.toml"]
